name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(python -m pip cache dir)" >> "$GITHUB_OUTPUT"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate || source .venv/Scripts/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black isort pre-commit

      - name: Run pre-commit
        run: |
          source .venv/bin/activate || source .venv/Scripts/activate
          pre-commit run --files $(git ls-files)

      - name: Run linters
        run: |
          source .venv/bin/activate || source .venv/Scripts/activate
          flake8 src/ tests/
          black --check src/ tests/
          isort --check-only src/ tests/

      - name: Test with pytest
        run: |
          source .venv/bin/activate || source .venv/Scripts/activate
          pytest --cov=src/gmail_automation --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
